sonar.projectKey=my-org-ebayou_rizki
sonar.organization=my-org-ebayou
sonar.sourceEncoding=UTF-8

# Sumber & test
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Coverage (dari Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# (opsional) Sesuaikan jika pakai monorepo:
# sonar.working.directory=.sonar
